apiVersion: apps/v1
kind: Deployment
metadata:
  name: notion-search
  namespace: notion-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notion-search
  template:
    metadata:
      labels:
        app: notion-search
    spec:
      containers:
      - name: notion-search
        image: your-dockerhub-username/notion-search:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: NOTION_API_KEY
          valueFrom:
            secretKeyRef:
              name: notion-secrets
              key: NOTION_API_KEY
        - name: NOTION_DATABASE_ID
          valueFrom:
            secretKeyRef:
              name: notion-secrets
              key: NOTION_DATABASE_ID
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: notion-secrets
              key: OPENAI_API_KEY
        volumeMounts:
        - name: qdrant-storage
          mountPath: /app/qdrant_storage
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: qdrant-storage
        persistentVolumeClaim:
          claimName: qdrant-pvc 