name: Model Monitoring

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run monitoring checks
        run: |
          python -c "from monitoring import setup_logging; from github_logging import setup_github_logging; setup_github_logging(); logger = setup_logging(); logger.info('Running monitoring checks...')"
